### ISSUE TITLE
New 5.4.0 release

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/communication#11]
https://github.com/pymc-devs/pymc/releases/tag/v5.4.0

Maybe we can focus on the 4 new contributors.

**Comment by purna135** [comment]
Ok, in this post, I'll highlight the new contributors, but I'm curious if we could start a new series called "Contributors/maintainer/some_title of the Month" to recognize new members or those who are doing outstanding work.

**Comment by purna135** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7069330224399695872

https://twitter.com/pymc_devs/status/1663566197768728576
