### ISSUE TITLE
New core dev: Jesse Grawbowski

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/communication#12]
Maybe we can do a social media card and a bit of a bio and post that on social media.

**Comment by twiecki** [comment]
Also talked with @canyon289 to do a youtube interview pymcon style.

**Comment by canyon289** [comment]
Yes

**Comment by twiecki** [comment]
@purna135 I believe this is completed too. Maybe you can post a link to the social media and close issues when completed.

**Comment by purna135** [comment]
sorry I forgot to close the issue, it's done
https://twitter.com/pymc_devs/status/1687489961581309952
https://www.linkedin.com/feed/update/urn:li:activity:7093252301275955200
