### ISSUE TITLE
Share on social: PyMC 2023 Interns

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/communication#13]
2023 Blog:  
https://www.pymc.io/blog/blog_gsoc_2023.html

Example shares from 2022:  
https://twitter.com/pymc_devs/status/1544712019630227460

Note: 
2022 social media cards are in Canva for reference.

cc: [@shreyas3156](https://github.com/shreyas3156), [@daniel-saunders-phil](https://github.com/daniel-saunders-phil), [GStechschulte](https://github.com/GStechschulte)

cc:  @purna135

**Comment by twiecki** [comment]
@purna135 did we do this? Can we close it?

**Comment by purna135** [comment]
yes it's done:
https://www.linkedin.com/feed/update/urn:li:activity:7094730908741627907
https://twitter.com/pymc_devs/status/1688972100210462733
