### ISSUE TITLE
New ADIA Lab sponsor

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/communication#6]

**Comment by purna135** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7040346948310056960

https://twitter.com/pymc_devs/status/1634586002315411456

**Comment by reshamas** [comment]
The second sponsor, ADIA, hasn't submitted their donation, so we shouldn't promote them until the payment has gone through.

For new sponsors, I can let you know once the payment is made and share a link to their Open Collective donation.
Then, we can officially call them a sponsor.

**Comment by purna135** [comment]
I am closing this for now. Please reopen this issue once we are ready to make an announcement.
