### ISSUE TITLE
Gitpod: can contribute to PyMC using Gitpod + instructions 

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/communication#9]
https://www.pymc.io/projects/docs/en/latest/contributing/using_gitpod.html

**Comment by reshamas** [comment]
@purna135 Are you able to share this video on pymc_devs social media:
https://youtu.be/jsjOmhUaKuU

Thank you.

**Comment by purna135** [comment]
Sure, will share it tomorrow

**Comment by purna135** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7058077468439494656

https://twitter.com/pymc_devs/status/1652320358249402368
